CREATE TABLE event(
id UUID DEFAULT gen_random_wid() PRIMARY KEY,
title  VARCHAR(100) NOT NULL,
description  VARCHAR(250) NOT NULL,
event_url  VARCHAR(100) NOT NULL,
date TIMESTAMP NOT NULL,
remote BOOLEAN NOT NULL

);